development:
  adapter: postgresql
  encoding: unicode
  database: chronr_development
  pool: 5
  username: postgres
  password:

test:
    adapter: postgresql
    encoding: unicode
    database: chronr_test
    pool: 5
    username: chronr
    password:

production:
    adapter: postgresql
    encoding: unicode
    database: chronr_production
    pool: 5
    username: chronr
    password: